name: gh-pages-deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      #  with:
      #    bun-version: latest
      # - uses: actions/cache@v4
      #   with:
      #     path: ~/.bun/install/cache
      #     key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
      - run: bun install
      - run: bun run build
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          enable_jekyll: false